version: '3.4'

networks:
  app_net:
    driver: bridge
    name: app_net

services:
  service.processamento:
    image: ${DOCKER_REGISTRY-}service.processamento
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ_HOST=rabbitmq # Nome do container do RabbitMQ na aplicação 1
      - RabbitMQ_PORT=5672
    networks:
      - app_net
